# ANTROUTE: train the CNN+LSTM + RADR STGNN + MLP Decoder, then score every edge

Runs on a **GPU** Colab runtime (Runtime -> Change runtime type -> T4 GPU).

Uses the merged `feature/mlp-decoder-joint-edge-risk` pipeline: CNN+LSTM -> RADR STGNN -> **MLP Decoder** ->
risk per road edge (matches the architecture diagram exactly; no classifier head, no averaging formula).

**Before you start**
1. `git push` the latest code from your PC (this notebook pulls it).
2. Wait for Drive for Desktop to finish syncing, so everyone's newest `labels_<name>.csv` files are in the cloud.
3. Frames folders on Drive: `MMDA_FRAMES_PILOT` (May 4), `MMDA_FRAMES` (May 4/6/8/11/13/15), `MMDA_FRAMES_B` (May 18/20/22/25).

Part 1 trains. Part 2 scores every extracted session and writes a risk value per road edge.

## 0. Check the GPU

## Config -- run this first, every time (including after any Runtime restart)
These names are used by every cell below. If the frames/checkpoint/scores already exist on Drive, you do NOT
need to re-run copying, training, or scoring -- just make sure **Drive is mounted** (run the `drive.mount(...)`
cell in section 1 -- safe to run again even if already mounted), run this config cell, then jump straight to
the results cell you need (9 or 13); they read what is already saved on Drive.

If a results cell says `FileNotFoundError` for a path under `/content/drive/...`, that almost always means
Drive isn't mounted in *this* session (a fresh runtime, not just a Restart) -- run `drive.mount(...)` again,
it doesn't matter that the file already exists on the actual Drive if this session can't see it yet.

In [1]:
RUN = "stgnn_edge_thesis"     # name of this run; change it (and re-run training) for a new experiment
EPOCHS = 10   # thesis Table 2
CKPT_DIR = "/content/drive/MyDrive/MMDA_CHECKPOINTS"
OUT = "/content/drive/MyDrive/MMDA_RISK_SCORES"

USE_TEXT = True   # False = --no-text (skip DistilBERT tweet embeddings entirely)
EMBEDDINGS_PATH = "/content/drive/MyDrive/MMDA_TEXT/embeddings.pt"   # copied there from your PC's
                                                                    # regenerated traffic_system/data/processed/embeddings.pt
TEXT_ARGS = f"--embeddings {EMBEDDINGS_PATH}" if USE_TEXT else "--no-text"

USE_CLASS_WEIGHTS = False  # True = class-weighted BCE, an ablation not described in the thesis
                           # (balances the Light/Medium/Heavy label skew, 57% Heavy)
CLASS_WEIGHT_ARGS = "--class-weights" if USE_CLASS_WEIGHTS else ""

In [2]:
import torch
print("GPU available:", torch.cuda.is_available(), "|", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no GPU - change the runtime type")

GPU available: True | Tesla T4

## 1. Setup: code, packages, and a fast local copy of the frames

In [3]:
from google.colab import drive; drive.mount("/content/drive")
!test -d /content/ANTROUTE && git -C /content/ANTROUTE pull || git clone -b dev https://github.com/Traffic-Forecasting-Thesis-Group/ANTROUTE.git /content/ANTROUTE
!pip install -q scipy
!git -C /content/ANTROUTE log --oneline -1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Already up to date.
5f514b30 (HEAD -> dev, origin/dev) Add class-weighted loss to counter the Light/Medium/Heavy label skew

In [4]:
# Copy the frames from Drive to the fast local disk (training reads thousands of images; Drive is slow).
# Safe to re-run: rsync only copies what is missing or changed, so an interrupted copy just resumes.
# Google Sheets shortcuts (*.gsheet) that Drive creates next to the CSVs cannot be copied and are skipped.
#
# Drive is a network mount (FUSE), and heavy I/O across many folders in one session can get rate-limited by
# Google, making a copy silently hang for hours with no error. RSYNC_TIMEOUT_SEC makes that fail fast instead.
# ONLY_DATES restricts a folder to specific date subfolders (plus the root CSVs) -- use it for a folder that
# keeps timing out, so you only pull the dates your current --split auto training run actually needs. Copy
# the rest later in a fresh session (Runtime -> Restart session resets Drive's rate-limit state).
import os, subprocess, csv
from pathlib import Path
FRAMES = {"pilot": "MMDA_FRAMES_PILOT", "a": "MMDA_FRAMES", "b": "MMDA_FRAMES_B"}   # local name -> Drive folder
ONLY_DATES = {"a": ["2026-05-04", "2026-05-06", "2026-05-08", "2026-05-11", "2026-05-13"],  # May 15 has no labels
              "b": ["2026-05-18", "2026-05-20"]}   # local name -> date subfolders to copy (May 22/25 have no labels yet)
RSYNC_TIMEOUT_SEC = 1800   # give up on one folder after this long instead of hanging forever
os.makedirs("/content/frames", exist_ok=True)
for local, folder in FRAMES.items():
    src = f"/content/drive/MyDrive/{folder}"
    if not os.path.isdir(src):
        print(f"{folder}: MISSING on Drive")
        continue
    dst = f"/content/frames/{local}"
    os.makedirs(dst, exist_ok=True)
    dates = ONLY_DATES.get(local)
    # csv files at the folder root, then just the wanted date subfolders (or everything, if no filter is set)
    includes = [f"--include={f.name}" for f in Path(src).glob("*.csv")]
    if dates:
        includes += [f"--include={d}/" for d in dates] + [f"--include={d}/**" for d in dates] + ["--exclude=*"]
    cmd = ["rsync", "-a", "--exclude=*.gsheet"] + includes + [f"{src}/", f"{dst}/"]
    try:
        result = subprocess.run(cmd, timeout=RSYNC_TIMEOUT_SEC)
        ok = result.returncode == 0
    except subprocess.TimeoutExpired:
        print(f"{folder}: TIMED OUT after {RSYNC_TIMEOUT_SEC}s - Drive is likely rate-limited. "
              f"Runtime -> Restart session, then re-run this cell (it resumes), or add an ONLY_DATES filter.")
        continue
    n_local = sum(1 for _ in Path(dst).rglob("*.jpg"))
    manifest = Path(dst) / "manifest.csv"
    if manifest.exists() and dates:
        with manifest.open() as f:
            n_expected = sum(1 for row in csv.DictReader(f) if row["frame_path"][:10] in dates)
    elif manifest.exists():
        n_expected = sum(1 for _ in csv.reader(manifest.open())) - 1
    else:
        n_expected = None
    complete = ok and n_expected is not None and n_local == n_expected
    note = f" (filtered to {dates})" if dates else ""
    print(f"{folder}{note}: {n_local}/{n_expected} frames copied | labels: {len(list(Path(dst).glob('labels*.csv')))} file(s) | "
          + ("OK" if complete else "NOT COMPLETE - run this cell again"))

MMDA_FRAMES_PILOT: 1735/1735 frames copied | labels: 1 file(s) | OK
MMDA_FRAMES: TIMED OUT after 1800s - Drive is likely rate-limited. Runtime -> Restart session, then re-run this cell (it resumes), or add an ONLY_DATES filter.
MMDA_FRAMES_B: TIMED OUT after 1800s - Drive is likely rate-limited. Runtime -> Restart session, then re-run this cell (it resumes), or add an ONLY_DATES filter.

In [5]:
# What labels do we have, and how would the 70/15/15 split look?
import sys; sys.path.insert(0, "/content/ANTROUTE/traffic_system")
from pathlib import Path
import collections, pandas as pd
from src.data.training_data import (assign_session_splits, describe_split, labelled_sessions, load_frames_table,
                                    load_label_lookup, session_of)
roots = [Path(f"/content/frames/{n}") for n in FRAMES if Path(f"/content/frames/{n}").exists()]
lookup = load_label_lookup(roots, human_only=True)
frames = load_frames_table(roots)
times = pd.to_datetime(frames.loc[frames["frame_path"].isin(lookup), "timestamp"], format="ISO8601")
per_session = collections.Counter(session_of(t) for t in times)
print("your labels per session:", {f"{d:%b %d} {s}": n for (d, s), n in sorted(per_session.items())})
print("\nsplit that --split auto will use (sessions need >= 100 labels):")
print(describe_split(assign_session_splits(labelled_sessions(roots, lookup, 100))))

your labels per session: {'May 04 AM': 11, 'May 04 PM': 913, 'May 06 AM': 579, 'May 06 PM': 612, 'May 08 AM': 457, 'May 08 PM': 471, 'May 11 AM': 1337, 'May 11 PM': 1554, 'May 13 AM': 808, 'May 13 PM': 991, 'May 18 AM': 897, 'May 18 PM': 951, 'May 20 AM': 100, 'May 20 PM': 720, 'May 22 AM': 388, 'May 22 PM': 411, 'May 25 AM': 699, 'May 25 PM': 856}

split that --split auto will use (sessions need >= 100 labels):
  train (11): May 04 PM, May 06 AM, May 06 PM, May 08 AM, May 08 PM, May 11 AM, May 11 PM, May 13 AM, May 13 PM, May 18 AM, May 18 PM
  val   (3): May 20 AM, May 20 PM, May 22 AM
  test  (3): May 22 PM, May 25 AM, May 25 PM

## 2. Train
The printed table above must show **train / val / test** sessions. With fewer than 3 labelled sessions there is no test set yet.

This model predicts a continuous **risk value per edge** (0 = free-flowing, 1 = heavy), trained against your
Light/Medium/Heavy labels mapped to 0 / 0.5 / 1 on edges that touch a labelled camera intersection. The metric to
watch is **MAE** (mean absolute error, lower is better) — not accuracy or F1, since this is regression, not
classification. A naive "always predict 0.5" baseline gets MAE ~0.33-0.5 depending on the label mix, so a trained
MAE clearly below that means the model is learning something real.

In [6]:
!mkdir -p {CKPT_DIR}
!cd /content/ANTROUTE/traffic_system && python scripts/train_stgnn_edge.py     --frames-root /content/frames/pilot /content/frames/a /content/frames/b     --human-only --split auto {TEXT_ARGS} {CLASS_WEIGHT_ARGS}     --epochs {EPOCHS} --batch-size 4 --num-workers 2     --out {CKPT_DIR}/{RUN}.pt

Streaming output truncated to the last 5000 lines.
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_015.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_015.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_016.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_016.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_017.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_017.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_018.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_018.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_019.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_019.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_020.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_020.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_021.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_021.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_022.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_022.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_023.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_023.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_024.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_024.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_025.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_025.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_026.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_026.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_027.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_027.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_028.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_028.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_16_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_16_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_001.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_001.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_002.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_002.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_003.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_003.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_004.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_004.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_005.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_005.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_006.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_006.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_007.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_007.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_008.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_008.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_009.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_009.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_010.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_010.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_011.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_011.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_012.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_012.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_013.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_013.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_014.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_014.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_015.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_015.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_016.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_016.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_017.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_017.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_018.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_018.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_019.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_019.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_020.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_020.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_021.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_021.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_022.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_022.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_023.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_023.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_024.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_024.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_025.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_025.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_026.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_026.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_027.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_027.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_028.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_15_028.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_16_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3020/20260525_16_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3011/20260525_15_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3011/20260525_15_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")

In [7]:
import pandas as pd
# Per-epoch results (also saved next to the checkpoint)
m = pd.read_csv(f"{CKPT_DIR}/{RUN}.metrics.csv")
display(m.round(4))

# The SAVED checkpoint is the epoch with lowest val_loss (that is what train_stgnn_edge.py selects,
# not lowest val_mae) -- report that one, since it is the model that will actually be used for scoring.
saved = m.loc[m["val_loss"].idxmin()]
best_mae_row = m.loc[m["val_mae"].idxmin()]
print(f"SAVED checkpoint: epoch {int(saved['epoch'])}  val_loss {saved['val_loss']:.4f}  val_mae {saved['val_mae']:.4f} "
      f"over {int(saved['val_n_edges'])} labelled edges")
if int(saved["epoch"]) != int(best_mae_row["epoch"]):
    print(f"(lowest val_mae was actually epoch {int(best_mae_row['epoch'])} at {best_mae_row['val_mae']:.4f} -- "
          f"not saved, since checkpoint selection uses val_loss)")
print("naive 'always predict 0.5' baseline: MAE ~0.33 for a balanced Light/Medium/Heavy label mix")

    epoch  train_loss  val_loss  val_mae  val_n_edges
0       1      0.7023    0.6504   0.3308         1212
1       2      0.6956    0.6401   0.3305         1212
2       3      0.6746    0.6576   0.3559         1212
3       4      0.6354    0.6575   0.3531         1212
4       5      0.6412    0.6570   0.3288         1212
5       6      0.6425    0.6668   0.3771         1212
6       7      0.6327    0.6769   0.3643         1212
7       8      0.6411    0.7243   0.4353         1212
8       9      0.6271    0.6547   0.3475         1212
9      10      0.6328    0.6732   0.3628         1212
10     11      0.6369    0.6779   0.3673         1212
11     12      0.6197    0.6709   0.3183         1212
12     13      0.6235    0.7157   0.3719         1212
13     14      0.6152    0.6750   0.3253         1212
14     15      0.6103    0.7218   0.3079         1212

SAVED checkpoint: epoch 2  val_loss 0.6401  val_mae 0.3305 over 1212 labelled edges
(lowest val_mae was actually epoch 15 at 0.3079 -- not saved, since checkpoint selection uses val_loss)
naive 'always predict 0.5' baseline: MAE ~0.33 for a balanced Light/Medium/Heavy label mix

### Optional ablations (run one at a time, with a new `RUN` name)
```
--no-time-features        # remove the time-in-session input
```
For a text-on run, copy your regenerated `embeddings.pt` to Drive and replace `--no-text` with
`--embeddings /content/drive/MyDrive/MMDA_TEXT/embeddings.pt`.

## 3. Score every session (run when extraction is complete)
Re-run the copy cell in section 1 first, so the frames extracted since then are on the local disk.
Output goes to Drive: `risk_edges.csv` (one row per window per road edge) and `risk_summary.json`
(edge count and MAE per split, for edges that touch a labelled camera).

In [8]:
!cd /content/ANTROUTE/traffic_system && python scripts/predict_congestion_risk.py     --checkpoint {CKPT_DIR}/{RUN}.pt     --frames-root /content/frames/pilot /content/frames/a /content/frames/b     --embeddings {EMBEDDINGS_PATH}     --out-dir {OUT} --batch-size 8 --num-workers 2

Streaming output truncated to the last 5000 lines.
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_004.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_004.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_006.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_006.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_007.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_007.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_008.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_008.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_009.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_009.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_010.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_010.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_012.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/870D7CDB0F6682870F898236FEB0AAA3_4085/20260525_17_012.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_011.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_011.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_012.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_012.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_013.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_013.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_014.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_014.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_015.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_015.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_016.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_016.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_017.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_017.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_018.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_018.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_019.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_019.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_020.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_020.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_021.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_021.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_022.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_022.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_023.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_023.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_024.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_024.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_025.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_025.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_026.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_026.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_027.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_027.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_028.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_028.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_029.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_16_029.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_001.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_001.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_002.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_002.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_003.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_003.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_004.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_004.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_005.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_005.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_006.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_006.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_007.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_007.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_008.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_008.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_009.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_009.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_010.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/B283A8C105D7340B4EDE2AD51DC7F279_3050/20260525_17_010.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_000.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_000.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_001.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_001.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_002.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_002.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_003.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_003.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_004.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_004.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_005.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_005.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_006.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_006.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_007.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_007.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")
/content/ANTROUTE/traffic_system/src/data/dataset.py:77: UserWarning: Frame listed in manifest but unreadable, skipping: /content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_008.jpg ([Errno 2] No such file or directory: '/content/frames/b/2026-05-25/F563F31E57FF54515F14BC36673F9EF9_8337 - Ayala NB 1/20260525_15_008.jpg')
  warnings.warn(f"Frame listed in manifest but unreadable, skipping: {path} ({e})")

In [9]:
import json
import pandas as pd
summary = json.load(open(f"{OUT}/risk_summary.json"))
display(pd.DataFrame(summary).T.round(4))   # edge_rows, labelled_edges, mae per split (train / val / test / infer)

edges = pd.read_csv(f"{OUT}/risk_edges.csv")
print(f"{len(edges)} edge-window rows written | {edges['camera_edge'].sum()} touch a labelled camera")
display(edges.head(10))
print("mean predicted risk per session:")
display(edges.groupby(["day", "session"])["risk"].mean().round(3))

,infer,test,train,val
checkpoint,/content/drive/MyDrive/MMDA_CHECKPOINTS/stgnn_...,/content/drive/MyDrive/MMDA_CHECKPOINTS/stgnn_...,/content/drive/MyDrive/MMDA_CHECKPOINTS/stgnn_...,/content/drive/MyDrive/MMDA_CHECKPOINTS/stgnn_...
windows,366,366,366,366
sessions,20,20,20,20
edges,2816,2816,2816,2816
camera_edges,37,37,37,37
splits,"{'edge_rows': 121088, 'labelled_edges': 8, 'ma...","{'edge_rows': 160512, 'labelled_edges': 1456, ...","{'edge_rows': 588544, 'labelled_edges': 5665, ...","{'edge_rows': 160512, 'labelled_edges': 1022, ..."

1030656 edge-window rows written | 13542 touch a labelled camera

,day,session,window_start,window_end,source_node_id,target_node_id,risk,camera_edge,split,weak_target
0,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067308,1723298722,0.5534,False,infer,NaN
1,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067330,21590503,0.5571,False,infer,NaN
2,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067330,6621954486,0.5602,False,infer,NaN
3,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067342,21590497,0.4281,True,infer,NaN
4,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067342,3403138097,0.4238,True,infer,NaN
5,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067355,750630860,0.5381,False,infer,NaN
6,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067458,32476435,0.5545,False,infer,NaN
7,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067458,32929569,0.5575,False,infer,NaN
8,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067458,32929677,0.5586,False,infer,NaN
9,2026-05-04,AM,2026-05-04T07:00:00,2026-05-04T07:30:00,12067461,12067466,0.5564,False,infer,NaN

mean predicted risk per session:

day         session
2026-05-04  AM         0.550
            PM         0.550
2026-05-06  AM         0.550
            PM         0.553
2026-05-08  AM         0.550
            PM         0.553
2026-05-11  AM         0.550
            PM         0.553
2026-05-13  AM         0.554
            PM         0.554
2026-05-15  AM         0.554
            PM         0.554
2026-05-18  AM         0.552
            PM         0.551
2026-05-20  AM         0.554
            PM         0.554
2026-05-22  AM         0.552
            PM         0.554
2026-05-25  AM         0.551
            PM         0.553
Name: risk, dtype: float64